/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import apptransi.Alumno;
import apptransi.Transi;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daso
 */
public class VistaAlumnos extends javax.swing.JFrame {

   private Transi transi;
  private DefaultTableModel tableModel;
 public VistaAlumnos() {
 initComponents();
 transi = new Transi();
 tblAlumnos.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
tableModel = (DefaultTableModel) tblAlumnos.getModel();
 mostrarAlumnos();
 mostrarEstadisticas();
 }

 private void mostrarAlumnos(){
 tableModel.setRowCount(transi.getAlumnos().size());
 for(int i=0; i<transi.getAlumnos().size(); i++){
 Alumno alumno = transi.getAlumnos().get(i);
 tableModel.setValueAt(alumno.getCodigo(), i, 0);
 tableModel.setValueAt(alumno.getNombre(), i, 1);
 tableModel.setValueAt(alumno.getModalidad(), i, 2);
 tableModel.setValueAt(alumno.getCalificacion().calcularPromedioFinal(), i, 3);
 }
 }

 private void mostrarEstadisticas(){
txtPFMayor.setText(String.valueOf(transi.calcularPromedioFinalMayor()));
 txtPFMenor.setText(String.valueOf(transi.calcularPromedioFinalMenor()));
 txtPromSalon.setText(String.valueOf(transi.calcularPromedioSalon()));
 }

private void mostrarCalificacion(){
int filaSeleccionada = tblAlumnos.getSelectedRow();
 if (filaSeleccionada != -1){
 JDialog vistaCalificacion = null;
 String codigoAlumno = tableModel.getValueAt(filaSeleccionada, 0).toString();
 String modalidad = tableModel.getValueAt(filaSeleccionada, 2).toString();
 if (modalidad.equals("Práctica")){
 vistaCalificacion = new VistaCalificacionPractica(this, true, transi, codigoAlumno);
 }
 else{
 vistaCalificacion = new VistaCalificacionTradicional(this, true, transi, codigoAlumno);
 }
 vistaCalificacion.setVisible(true);
 vistaCalificacion.dispose();
 mostrarAlumnos();
 mostrarEstadisticas();
 }
 }


 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbxModalidad = new javax.swing.JComboBox();
        btnRegistrarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnCalificacion = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtPFMayor = new javax.swing.JTextField();
        txtPFMenor = new javax.swing.JTextField();
        txtPromSalon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Tipo");

        jLabel4.setText("PfMayor");

        jLabel5.setText("PfMenor");

        jLabel6.setText("Promedio");

        cbxModalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tradicional", "Práctica" }));

        btnRegistrarAlumno.setText("Agregar");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(tblAlumnos);

        btnCalificacion.setText("Calificación");
        btnCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtPFMayor.setText("jTextField3");

        txtPFMenor.setText("jTextField4");

        txtPromSalon.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxModalidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                                .addComponent(txtCodigo))
                            .addGap(185, 185, 185)
                            .addComponent(btnRegistrarAlumno))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCalificacion)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPromSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPFMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPFMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarAlumno))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalificacion)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPFMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPFMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPromSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionActionPerformed
        mostrarCalificacion();
    }//GEN-LAST:event_btnCalificacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int filaSeleccionada = tblAlumnos.getSelectedRow();
 if (filaSeleccionada != -1){
 String codigoAlumno = tableModel.getValueAt(filaSeleccionada, 0).toString();
 transi.eliminarAlumno(codigoAlumno);
 mostrarAlumnos();
 mostrarEstadisticas();
 }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
       String codigo = txtCodigo.getText();
 String nombre = txtNombre.getText();
 String modalidad = cbxModalidad.getSelectedItem().toString();
 if (! codigo.equals("") && ! nombre.equals("")){
 if (transi.buscarAlumno(codigo) == null){
 transi.registrarAlumno(codigo, nombre, modalidad);
 mostrarAlumnos();
 mostrarEstadisticas();
 txtCodigo.setText("");
 txtNombre.setText("");
 txtCodigo.requestFocusInWindow();
 }
 else {
 JOptionPane.showMessageDialog(rootPane, "Código ya existe");
 }
 }
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificacion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JComboBox cbxModalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPFMayor;
    private javax.swing.JTextField txtPFMenor;
    private javax.swing.JTextField txtPromSalon;
    // End of variables declaration//GEN-END:variables
}
